### ISSUE TITLE
Tracking a query that was added via graph can fail if `--hints` is not specified

### ISSUE THREAD

**Issue by Zeitsperre** [ESGF/esgf-download#15]
Not sure why this would be happening, but it seems like `--hints` must be specified when `--distrib=True`.

```
[2023-07-24 13:23:03]  DEBUG     root
Locals:
{
    'self': Context(
        config=Config(
            paths=Paths(
                auth=PosixPath('/home/me/.esgpull/auth'),
                data=PosixPath('/elsewhere/me/synda/data'),
                db=PosixPath('/home/me/.esgpull/db'),
                log=PosixPath('/home/me/.esgpull/log'),
                tmp=PosixPath('/home/me/.esgpull/tmp')
            ),
            credentials=Credentials(filename='credentials.toml'),
            cli=Cli(page_size=20),
            db=Db(filename='esgpull.db'),
            download=Download(chunk_size=67108864, http_timeout=20, max_concurrent=5),
            api=API(
                index_node='esgf-node.ipsl.upmc.fr',
                http_timeout=20,
                max_concurrent=5,
                page_limit=50,
                default_options=DefaultOptions(
                    distrib='true',
                    latest='true',
                    replica='none',
                    retracted='false'
                )
            ),
            _raw={'paths': {'auth': '/home/me/.esgpull/auth', 'data': 
'/tank/me/synda/data', 'db': '/home/me/.esgpull/db', 'log': '/home/me/.esgpull/log', 
'tmp': '/home/me/.esgpull/tmp'}, 'credentials': {'filename': 'credentials.toml'}, 'cli': 
{'page_size': 20}, 'db': {'filename': 'esgpull.db'}, 'download': {'chunk_size': 67108864, 
'http_timeout': 20, 'max_concurrent': 5}, 'api': {'index_node': 'esgf-node.ipsl.upmc.fr', 
'http_timeout': 20, 'max_concurrent': 5, 'page_limit': 50, 'default_options': {'distrib': 
'true'}}},
            _config_file=PosixPath('/home/me/.esgpull/config.toml')
        ),
        noraise=True
    ),
    'file': True,
    'hints': [{}],
    'offset': 0,
    'max_hits': None,
    'page_limit': 50,
    'fields_param': ['*'],
    'date_from': None,
    'date_to': None,
    'queries': (
        Query(
            name='<3cb4e3>',
            tracked=True,
            options=Options(
                distrib=(0, False),
                latest=(0, False),
                replica=(2, None),
                retracted=(0, False)
            ),
            selection=Selection(
                activity_id=['CMIP', 'ScenarioMIP'],
                experiment_id=['ssp245', 'ssp370'],
                member_id='r1i1p1f2',
                project='CMIP6',
                source_id=['CNRM-CM6-1', 'CNRM-ESM2-1', 'MIROC-ES2L', 'UKESM1-0-LL'],
                table_id='day',
                variable_id=['pr', 'tasmax', 'tasmin']
            )
        ),
    ),
    'hits': [0],
    'results': [],
    'not_distrib': Query(name='<26887c>', options=Options(distrib=(0, False))),
    'query': Query(
        name='<3cb4e3>',
        tracked=True,
        options=Options(
            distrib=(0, False),
            latest=(0, False),
            replica=(2, None),
            retracted=(0, False)
        ),
        selection=Selection(
            activity_id=['CMIP', 'ScenarioMIP'],
            experiment_id=['ssp245', 'ssp370'],
            member_id='r1i1p1f2',
            project='CMIP6',
            source_id=['CNRM-CM6-1', 'CNRM-ESM2-1', 'MIROC-ES2L', 'UKESM1-0-LL'],
            table_id='day',
            variable_id=['pr', 'tasmax', 'tasmin']
        )
    ),
    'query_hints': {},
    'query_max_hits': 0
}


[2023-07-24 13:23:03]  ERROR     root

Traceback (most recent call last):
  File "/home/me/mambaforge//envs/esgf/lib/python3.11/site-packages/esgpull/tui.py", line 154, in logging
    yield
  File "/home/me/mambaforge/envs/esgf/lib/python3.11/site-packages/esgpull/cli/update.py", line 93, in update
    qf_results = esg.context.prepare_search_distributed(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/mambaforge/envs/esgf/lib/python3.11/site-packages/esgpull/context.py", line 421, in prepare_search_distributed
    nodes = query_hints["index_node"]
            ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'index_node'
```

**Comment by Zeitsperre** [comment]
More information:
```
$ esgpull show
<0ec8e4>
└── distrib:       True                                                                       
    latest:        False                                                                      
    replica:       None                                                                       
    retracted:     False                                                                      
    activity_id:   CMIP, ScenarioMIP                                                          
    experiment_id: ssp245, ssp370                                                             
    member_id:     r1i1p1f1                                                                   
    project:       CMIP6                                                                      
    source_id:     ACCESS-CM2, ACCESS-ESM1-5, BCC-CSM2-MR, CMCC-ESM2, CanESM5, CanESM5-1,     
                   EC-Earth3, EC-Earth3-CC, EC-Earth3-Veg, FGOALS-g3, GFDL-ESM4, INM-CM5-0,   
                   IPSL-CM6A-LR, KACE-1-0-G, MIROC6, MPI-ESM1-2-HR, MPI-ESM1-2-LR, MRI-ESM2-0,
                   NESM3, NorESM2-LM, NorESM2-MM, TaiESM1                                     
    table_id:      day                                                                        
    variable_id:   pr, tasmax, tasmin                                                         
<d297dd>
└── distrib:       True                                            
    latest:        False                                           
    replica:       None                                            
    retracted:     False                                           
    activity_id:   CMIP, ScenarioMIP                               
    experiment_id: ssp245, ssp370                                  
    member_id:     r1i1p1f2                                        
    project:       CMIP6                                           
    source_id:     CNRM-CM6-1, CNRM-ESM2-1, MIROC-ES2L, UKESM1-0-LL
    table_id:      day                                             
    variable_id:   pr, tasmax, tasmin

$ esgpull update
Found 531 files.
KeyError: 'index_node'
See /home/me/.esgpull/log/esgpull-update-2023-07-24_17-47-36.log for error log.
Aborted!
```

**Comment by svenrdz** [comment]
Hi @Zeitsperre

Thanks, I can reproduce the error with your example queries. I am suspecting a bug in the code, directly related to the fact that your second query `d297dd` returns 0 files exactly. I'll push a fix for it.
In the meantime, you can still run the update command by specifying queries this way:
```sh
esgpull update 0ec8e4
```

For the record, I use this trick to "test" a query, and know the number of datasets/files associated with it:
```
$ esgpull search --require d2 -0
Found 0 datasets.

$ esgpull search --require d2 --file -0
Found 0 files.
```

Also, to be transparent about why hints appear in this traceback, it is due to the way metadata is fetched in the `--distrib=True` case. The same procedure as for `--hints` is used to fetch the exact number of file per index node. A number of queries are then dispatched to each node, where each query is local (eg `--distrib=False`) to the index node it has been sent to.
